modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ejektaflex/Kambrik/issues"
license = "GPL 3.0"

[[mods]]
modId = "kambrik"
version = "${version}"
displayName = "Kambrik"
authors = "Me!"
description = '''
A Light-weight Kotlin Library Mod!
'''
#logoFile = ""

[[dependencies.kambrik]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kambrik]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
